//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 03/07/2016 10:55:03
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace MediaAppSample.Core.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class Account
    {
        
        private static ResourceLoader resourceLoader;
        
        static Account()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Account).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Account");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Account");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Authenticating..."
        /// </summary>
        public static string TextAuthenticating
        {
            get
            {
                return resourceLoader.GetString("TextAuthenticating");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Authentication failed. Try again later."
        /// </summary>
        public static string TextAuthenticationFailed
        {
            get
            {
                return resourceLoader.GetString("TextAuthenticationFailed");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Creating account..."
        /// </summary>
        public static string TextCreatingAccount
        {
            get
            {
                return resourceLoader.GetString("TextCreatingAccount");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Signing out..."
        /// </summary>
        public static string TextSigningOut
        {
            get
            {
                return resourceLoader.GetString("TextSigningOut");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sign out"
        /// </summary>
        public static string TextSignout
        {
            get
            {
                return resourceLoader.GetString("TextSignout");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Are you sure you want to sign out?"
        /// </summary>
        public static string TextSignoutConfirmation
        {
            get
            {
                return resourceLoader.GetString("TextSignoutConfirmation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Username was not found!"
        /// </summary>
        public static string TextUsernameNotFound
        {
            get
            {
                return resourceLoader.GetString("TextUsernameNotFound");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Validating username..."
        /// </summary>
        public static string TextValidatingUsername
        {
            get
            {
                return resourceLoader.GetString("TextValidatingUsername");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "An error occurred while attempting to use your {0} profile to register an account. Please try again later."
        /// </summary>
        public static string TextWebAccountManagerRegisterAccountFailure
        {
            get
            {
                return resourceLoader.GetString("TextWebAccountManagerRegisterAccountFailure");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Retrieving your {0} profile..."
        /// </summary>
        public static string TextWebAccountManagerRetrievingProfile
        {
            get
            {
                return resourceLoader.GetString("TextWebAccountManagerRetrievingProfile");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sign-In / Sign-Up with an account that you can associate with MediaAppSample."
        /// </summary>
        public static string TextWebAccountManagerSignUpDescription
        {
            get
            {
                return resourceLoader.GetString("TextWebAccountManagerSignUpDescription");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Forgot Password"
        /// </summary>
        public static string ViewTitleForgotPassword
        {
            get
            {
                return resourceLoader.GetString("ViewTitleForgotPassword");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sign In"
        /// </summary>
        public static string ViewTitleSignIn
        {
            get
            {
                return resourceLoader.GetString("ViewTitleSignIn");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sign Up"
        /// </summary>
        public static string ViewTitleSignUp
        {
            get
            {
                return resourceLoader.GetString("ViewTitleSignUp");
            }
        }
    }
}
