//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 02/10/2016 12:03:41
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace MediaAppSample.Core.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class Location
    {
        
        private static ResourceLoader resourceLoader;
        
        static Location()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Location).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Location");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Location");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Finding your location..."
        /// </summary>
        public static string TextDeterminingLocation
        {
            get
            {
                return resourceLoader.GetString("TextDeterminingLocation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "{0} {1} away"
        /// </summary>
        public static string TextDistanceAwayDisplay
        {
            get
            {
                return resourceLoader.GetString("TextDistanceAwayDisplay");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Determining address..."
        /// </summary>
        public static string TextGeocodingAddress
        {
            get
            {
                return resourceLoader.GetString("TextGeocodingAddress");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kilometers"
        /// </summary>
        public static string TextKilomentersLong
        {
            get
            {
                return resourceLoader.GetString("TextKilomentersLong");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "km"
        /// </summary>
        public static string TextKilomentersShort
        {
            get
            {
                return resourceLoader.GetString("TextKilomentersShort");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Miles"
        /// </summary>
        public static string TextMilesLong
        {
            get
            {
                return resourceLoader.GetString("TextMilesLong");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "mi"
        /// </summary>
        public static string TextMilesShort
        {
            get
            {
                return resourceLoader.GetString("TextMilesShort");
            }
        }
    }
}
