//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 04/27/2016 09:17:20
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace MediaAppSample.Core.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class Resources
    {
        
        private static ResourceLoader resourceLoader;
        
        static Resources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Resources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Resources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Resources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Welcome to MediaAppSample!"
        /// </summary>
        public static string ApplicationDescription
        {
            get
            {
                return resourceLoader.GetString("ApplicationDescription");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "MediaAppSample"
        /// </summary>
        public static string ApplicationName
        {
            get
            {
                return resourceLoader.GetString("ApplicationName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Please describe what you were doing when the problem occurred:
        ///--------------------
        ///
        ///
        ///--------------------"
        /// </summary>
        public static string ApplicationProblemEmailBodyTemplate
        {
            get
            {
                return resourceLoader.GetString("ApplicationProblemEmailBodyTemplate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "{0} {1} auto-generated problem report"
        /// </summary>
        public static string ApplicationProblemEmailSubjectTemplate
        {
            get
            {
                return resourceLoader.GetString("ApplicationProblemEmailSubjectTemplate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "A problem occurred the last time you ran this application. Would you like to send us an email to report it?"
        /// </summary>
        public static string ApplicationProblemPromptMessage
        {
            get
            {
                return resourceLoader.GetString("ApplicationProblemPromptMessage");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Problem Report"
        /// </summary>
        public static string ApplicationProblemPromptTitle
        {
            get
            {
                return resourceLoader.GetString("ApplicationProblemPromptTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Check out {0} from the Windows Store!
        ///
        ///{1}"
        /// </summary>
        public static string ApplicationSharingBodyText
        {
            get
            {
                return resourceLoader.GetString("ApplicationSharingBodyText");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "madenwal@microsoft.com"
        /// </summary>
        public static string ApplicationSupportEmailAddress
        {
            get
            {
                return resourceLoader.GetString("ApplicationSupportEmailAddress");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Please provide and feedback you'd like to share with support:
        ///--------------------
        ///
        ///
        ///--------------------
        ///
        ///"
        /// </summary>
        public static string ApplicationSupportEmailBodyTemplate
        {
            get
            {
                return resourceLoader.GetString("ApplicationSupportEmailBodyTemplate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Feedback for {0} {1}"
        /// </summary>
        public static string ApplicationSupportEmailSubjectTemplate
        {
            get
            {
                return resourceLoader.GetString("ApplicationSupportEmailSubjectTemplate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "@madenwal"
        /// </summary>
        public static string ApplicationSupportTwitterUsername
        {
            get
            {
                return resourceLoader.GetString("ApplicationSupportTwitterUsername");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Theme will be applied the next time you launch the application."
        /// </summary>
        public static string ApplicationThemeStatus
        {
            get
            {
                return resourceLoader.GetString("ApplicationThemeStatus");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Would you like to send an e-mail with feedback instead?"
        /// </summary>
        public static string PromptRateApplicationEmailFeedbackMessage
        {
            get
            {
                return resourceLoader.GetString("PromptRateApplicationEmailFeedbackMessage");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Share feedback"
        /// </summary>
        public static string PromptRateApplicationEmailFeedbackTitle
        {
            get
            {
                return resourceLoader.GetString("PromptRateApplicationEmailFeedbackTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Would you like to rate this application and provide feedback on how we can make things better?"
        /// </summary>
        public static string PromptRateApplicationMessage
        {
            get
            {
                return resourceLoader.GetString("PromptRateApplicationMessage");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Rate Application"
        /// </summary>
        public static string PromptRateApplicationTitle
        {
            get
            {
                return resourceLoader.GetString("PromptRateApplicationTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "LeftToRight"
        /// </summary>
        public static string ResourceFlowDirection
        {
            get
            {
                return resourceLoader.GetString("ResourceFlowDirection");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "en-US"
        /// </summary>
        public static string ResourceLanguage
        {
            get
            {
                return resourceLoader.GetString("ResourceLanguage");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "About"
        /// </summary>
        public static string TextAbout
        {
            get
            {
                return resourceLoader.GetString("TextAbout");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Allow"
        /// </summary>
        public static string TextAllow
        {
            get
            {
                return resourceLoader.GetString("TextAllow");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Cancel"
        /// </summary>
        public static string TextCancel
        {
            get
            {
                return resourceLoader.GetString("TextCancel");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Canceled..."
        /// </summary>
        public static string TextCancellationRequested
        {
            get
            {
                return resourceLoader.GetString("TextCancellationRequested");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Details"
        /// </summary>
        public static string TextDetails
        {
            get
            {
                return resourceLoader.GetString("TextDetails");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Downloading..."
        /// </summary>
        public static string TextDownloading
        {
            get
            {
                return resourceLoader.GetString("TextDownloading");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "An unexpected error has occured. We apologize for any inconveniences here and we will be working to resolve this soon."
        /// </summary>
        public static string TextErrorGeneric
        {
            get
            {
                return resourceLoader.GetString("TextErrorGeneric");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Home"
        /// </summary>
        public static string TextHome
        {
            get
            {
                return resourceLoader.GetString("TextHome");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Loading..."
        /// </summary>
        public static string TextLoading
        {
            get
            {
                return resourceLoader.GetString("TextLoading");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Not right now"
        /// </summary>
        public static string TextMaybeLater
        {
            get
            {
                return resourceLoader.GetString("TextMaybeLater");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Movies"
        /// </summary>
        public static string TextMovies
        {
            get
            {
                return resourceLoader.GetString("TextMovies");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No"
        /// </summary>
        public static string TextNo
        {
            get
            {
                return resourceLoader.GetString("TextNo");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "N/A"
        /// </summary>
        public static string TextNotApplicable
        {
            get
            {
                return resourceLoader.GetString("TextNotApplicable");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "OK"
        /// </summary>
        public static string TextOk
        {
            get
            {
                return resourceLoader.GetString("TextOk");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pin to Start"
        /// </summary>
        public static string TextPinToStart
        {
            get
            {
                return resourceLoader.GetString("TextPinToStart");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Please wait..."
        /// </summary>
        public static string TextPleaseWait
        {
            get
            {
                return resourceLoader.GetString("TextPleaseWait");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Privacy Statement"
        /// </summary>
        public static string TextPrivacyStatement
        {
            get
            {
                return resourceLoader.GetString("TextPrivacyStatement");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Anonymous usage data may be collected to improve the application.  Outside of that, this app does not collection any information about you nor transmit any information except that which you would normally expect in any web request (such as IP address). If you choose to enable location services, then you last known location is stored in the app anonymously so that the app loads quicker the next time it is launched."
        /// </summary>
        public static string TextPrivacyStatementDescription
        {
            get
            {
                return resourceLoader.GetString("TextPrivacyStatementDescription");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Rate Application"
        /// </summary>
        public static string TextRateApp
        {
            get
            {
                return resourceLoader.GetString("TextRateApp");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Refresh"
        /// </summary>
        public static string TextRefresh
        {
            get
            {
                return resourceLoader.GetString("TextRefresh");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Related Movies"
        /// </summary>
        public static string TextRelatedMovies
        {
            get
            {
                return resourceLoader.GetString("TextRelatedMovies");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Related TV"
        /// </summary>
        public static string TextRelatedTV
        {
            get
            {
                return resourceLoader.GetString("TextRelatedTV");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Settings"
        /// </summary>
        public static string TextSettings
        {
            get
            {
                return resourceLoader.GetString("TextSettings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Share"
        /// </summary>
        public static string TextShare
        {
            get
            {
                return resourceLoader.GetString("TextShare");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sort"
        /// </summary>
        public static string TextSort
        {
            get
            {
                return resourceLoader.GetString("TextSort");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sorting..."
        /// </summary>
        public static string TextSorting
        {
            get
            {
                return resourceLoader.GetString("TextSorting");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Submit"
        /// </summary>
        public static string TextSubmit
        {
            get
            {
                return resourceLoader.GetString("TextSubmit");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "General"
        /// </summary>
        public static string TextTitleGeneral
        {
            get
            {
                return resourceLoader.GetString("TextTitleGeneral");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "TV"
        /// </summary>
        public static string TextTV
        {
            get
            {
                return resourceLoader.GetString("TextTV");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Unpin from Start"
        /// </summary>
        public static string TextUnpinFromStart
        {
            get
            {
                return resourceLoader.GetString("TextUnpinFromStart");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Yes"
        /// </summary>
        public static string TextYes
        {
            get
            {
                return resourceLoader.GetString("TextYes");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "About"
        /// </summary>
        public static string ViewTitleAbout
        {
            get
            {
                return resourceLoader.GetString("ViewTitleAbout");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Privacy Policy"
        /// </summary>
        public static string ViewTitlePrivacyPolicy
        {
            get
            {
                return resourceLoader.GetString("ViewTitlePrivacyPolicy");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Settings"
        /// </summary>
        public static string ViewTitleSettings
        {
            get
            {
                return resourceLoader.GetString("ViewTitleSettings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Terms of Service"
        /// </summary>
        public static string ViewTitleTermsOfService
        {
            get
            {
                return resourceLoader.GetString("ViewTitleTermsOfService");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Welcome!"
        /// </summary>
        public static string ViewTitleWelcome
        {
            get
            {
                return resourceLoader.GetString("ViewTitleWelcome");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "See more"
        /// </summary>
        public static string TextSeeMore
        {
            get
            {
                return resourceLoader.GetString("TextSeeMore");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "All genres"
        /// </summary>
        public static string TextGenreDefault
        {
            get
            {
                return resourceLoader.GetString("TextGenreDefault");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Recent"
        /// </summary>
        public static string TextRecent
        {
            get
            {
                return resourceLoader.GetString("TextRecent");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "hr"
        /// </summary>
        public static string TextHour
        {
            get
            {
                return resourceLoader.GetString("TextHour");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "hrs"
        /// </summary>
        public static string TextHours
        {
            get
            {
                return resourceLoader.GetString("TextHours");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "min"
        /// </summary>
        public static string TextMinute
        {
            get
            {
                return resourceLoader.GetString("TextMinute");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "mins"
        /// </summary>
        public static string TextMinutes
        {
            get
            {
                return resourceLoader.GetString("TextMinutes");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Released date: {0}"
        /// </summary>
        public static string TextTrailerDesciption
        {
            get
            {
                return resourceLoader.GetString("TextTrailerDesciption");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sneak Peek - {0}"
        /// </summary>
        public static string TextTrailerTitle
        {
            get
            {
                return resourceLoader.GetString("TextTrailerTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Release Date: {0}"
        /// </summary>
        public static string TextSneakPeekDescrption
        {
            get
            {
                return resourceLoader.GetString("TextSneakPeekDescrption");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sneak Peek - {0}"
        /// </summary>
        public static string TextSneakPeekTitle
        {
            get
            {
                return resourceLoader.GetString("TextSneakPeekTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Season {0}, Episode {1}"
        /// </summary>
        public static string TextTvEpisodeSubtitle
        {
            get
            {
                return resourceLoader.GetString("TextTvEpisodeSubtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "All seasons"
        /// </summary>
        public static string TextSeasonsDefault
        {
            get
            {
                return resourceLoader.GetString("TextSeasonsDefault");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "A-Z"
        /// </summary>
        public static string TextAZ
        {
            get
            {
                return resourceLoader.GetString("TextAZ");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Year"
        /// </summary>
        public static string TextYear
        {
            get
            {
                return resourceLoader.GetString("TextYear");
            }
        }
    }
}
