//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 03/07/2016 10:55:09
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace MediaAppSample.Core.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class Search
    {
        
        private static ResourceLoader resourceLoader;
        
        static Search()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Search).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Search");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Search");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Search"
        /// </summary>
        public static string ButtonTextSearch
        {
            get
            {
                return resourceLoader.GetString("ButtonTextSearch");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Searching '{0}'..."
        /// </summary>
        public static string TextSearching
        {
            get
            {
                return resourceLoader.GetString("TextSearching");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "{0} search results for '{1}'"
        /// </summary>
        public static string TextSearchResultsCount
        {
            get
            {
                return resourceLoader.GetString("TextSearchResultsCount");
            }
        }
    }
}
